from config.settings import Configs

settings = Configs.get_gmail_service_config()

EXTRACTION_PROVIDER = settings.EXTRACTION_PROVIDER

GEMINI_API_KEY = settings.GEMINI_API_KEY
GEMINI_MODEL = settings.GEMINI_MODEL

AZURE_OPENAI_ENDPOINT = settings.AZURE_OPENAI_ENDPOINT
AZURE_OPENAI_API_KEY = settings.AZURE_OPENAI_API_KEY
AZURE_OPENAI_DEPLOYMENT = settings.AZURE_OPENAI_DEPLOYMENT
AZURE_OPENAI_REASONING_EFFORT = settings.AZURE_OPENAI_REASONING_EFFORT
AZURE_OPENAI_TIMEOUT_SECONDS = settings.AZURE_OPENAI_TIMEOUT_SECONDS
AZURE_OPENAI_MAX_INPUT_CHARS = settings.AZURE_OPENAI_MAX_INPUT_CHARS

GMAIL_CREDENTIALS_FILE = settings.GMAIL_CREDENTIALS_FILE
GMAIL_REDIRECT_URI = settings.GMAIL_REDIRECT_URI
GMAIL_FRONTEND_RETURN_URL = settings.GMAIL_FRONTEND_RETURN_URL
GMAIL_QUERY = settings.QUERY
STATE_FILE = settings.STATE_FILE
